layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

languages:
  - name: CoffeeScript
    image_url: assets/images/coffeescript.svg

  - name: CSS
    image_url: assets/images/css.svg

  - name: HTML
    image_url: assets/images/html.svg

  - name: JavaScript
    image_url: assets/images/javascript.svg

  - name: PHP
    image_url: assets/images/php.svg

  - name: Sass
    image_url: assets/images/sass.svg

build-tools:
  - name: Bower
    image_url: assets/images/bower.svg

  - name: Brunch
    image_url: assets/images/brunch.svg

  - name: Docker
    image_url: assets/images/docker.svg

  - name: Grunt
    image_url: assets/images/grunt.svg

  - name: Gulp
    image_url: assets/images/gulp.svg

  - name: Webpack
    image_url: assets/images/webpack.svg

frameworks:
  - name: Bootstrap
    image_url: assets/images/bootstrap.svg
 
  - name: Compass
    image_url: assets/images/compass.svg

  - name: Foundation
    image_url: assets/images/foundation.svg

  - name: Gatsby
    image_url: assets/images/gatsby.svg

  - name: Jasmine
    image_url: assets/images/jasmine.svg

  - name: Kendo UI
    image_url: assets/images/kendo-ui.svg

  - name: Knockout
    image_url: assets/images/knockout.svg

libraries:
  - name: D3
    image_url: assets/images/d3.svg

  - name: GreenSock
    image_url: assets/images/greensock.svg
 
  - name: jQuery
    image_url: assets/images/jquery.svg

  - name: React
    image_url: assets/images/react.svg

version-control:
  - name: Git
    image_url: assets/images/git.svg

  - name: Mercurial
    image_url: assets/images/mercurial.svg
